name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release
  DOCKERHUB_OWNER: moaadkhamlich
  DOCKER_IMAGE_NAME: semidiscreteot-builder
  LIBRARY_IMAGE_NAME: semidiscreteot
  GEOGRAM_DIR: /usr/local/geogram

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push library Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.library
        push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        tags: |
          ${{ env.DOCKERHUB_OWNER }}/${{ env.LIBRARY_IMAGE_NAME }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
