name: Build and Deploy Documentation

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz
        
    - name: Configure Doxygen
      run: |
        # Update Doxyfile for GitHub Pages
        sed -i 's|OUTPUT_DIRECTORY.*|OUTPUT_DIRECTORY = ./docs|g' Doxyfile
        sed -i 's|HTML_OUTPUT.*|HTML_OUTPUT = html|g' Doxyfile
        
    - name: Generate Documentation
      run: |
        doxygen Doxyfile
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload Documentation
      uses: actions/upload-pages-artifact@v3
      with:
        path: './docs/html'

  deploy-docs:
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    needs: build-docs
    runs-on: ubuntu-latest
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4